<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Classification – Statistical Learning in R for Social Sciences</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./02_linear_regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7f74b8793d6bf6dbb36f0c47797f70b8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background: #00868B;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03_classification.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Classification</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Classification</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Learning in R for Social Sciences</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_introduction_to_statistical_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Statistical Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_classification.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link active" data-scroll-target="#logistic-regression"><span class="header-section-number">1</span> Logistic regression</a>
  <ul class="collapse">
  <li><a href="#multiple-logistic-regression" id="toc-multiple-logistic-regression" class="nav-link" data-scroll-target="#multiple-logistic-regression"><span class="header-section-number">1.1</span> Multiple Logistic Regression</a></li>
  <li><a href="#multinomial-logistic-regression" id="toc-multinomial-logistic-regression" class="nav-link" data-scroll-target="#multinomial-logistic-regression"><span class="header-section-number">1.2</span> Multinomial Logistic Regression</a></li>
  </ul></li>
  <li><a href="#generative-models-for-classification" id="toc-generative-models-for-classification" class="nav-link" data-scroll-target="#generative-models-for-classification"><span class="header-section-number">2</span> Generative Models for Classification</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-note no-icon callout-titled" title="Dataset: `bank_marketing_dataset`">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Dataset: <code>bank_marketing_dataset</code>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>bank_marketing_dataset</code> dataset is a social and behavioral dataset that seeks to capture the demographic, financial, and campaign-related factors that influence whether a bank client decides to subscribe to a term deposit following a direct marketing campaign. The fundamental research question behind this dataset is: <em>what characteristics of a client and of the marketing contact predict the decision to subscribe to a financial product, and how strongly does each factor contribute?</em> This dataset is publicly available on the <a href="https://archive.ics.uci.edu/dataset/222/bank+marketing">UCI Machine Learning Repository</a>. The dataset contains 4,521 observations, where each observation represents one individual client contacted during a phone-based marketing campaign run by a Portuguese banking institution. For each client, 17 variables have been recorded. One of these variables is the outcome we want to predict (dependent variable), and the remaining 16 are potential predictors (independent variables). The variables are as follows:</p>
<ul>
<li><p><code>age</code> records the age of the client in years,</p></li>
<li><p><code>job</code> describes the type of occupation of the client within the different categories,</p></li>
<li><p><code>marital</code> records the marital status of the client, categorized as married, single, or divorced (where divorced also includes widowed),</p></li>
<li><p><code>education</code> indicates the highest level of education the client has completed, with categories primary, secondary, and tertiary,</p></li>
<li><p><code>default</code> indicates whether the client has credit currently in default (“yes” or “no”),</p></li>
<li><p><code>balance</code> records the average annual balance held in the client’s bank account, measured in euros,</p></li>
<li><p><code>housing</code> indicates whether the client has an active housing loan (“yes” or “no”),</p></li>
<li><p><code>loan</code> indicates whether the client has an active personal loan (“yes” or “no”),</p></li>
<li><p><code>contact</code> describes the type of communication channel used to contact the client, with categories cellular, telephone, and unknown,</p></li>
<li><p><code>day</code> records the day of the month on which the client was last contacted,</p></li>
<li><p><code>month</code> records the month of the year in which the client was last contacted,</p></li>
<li><p><code>duration</code> records the duration of the last contact with the client in seconds (this variable is only known after the call has ended, and therefore should be used with caution in predictive modeling),</p></li>
<li><p><code>campaign</code> records the total number of times the client was contacted during the current marketing campaign,</p></li>
<li><p><code>pdays</code> records the number of days that elapsed since the client was last contacted in a previous campaign (-1 indicates the client had not been previously contacted),</p></li>
<li><p><code>previous</code> records the total number of times the client was contacted before the current campaign,</p></li>
<li><p><code>poutcome</code> describes the outcome of the previous marketing campaign for this client, with categories success, failure, other, and unknown,</p></li>
<li><p><code>y</code> records whether the client ultimately subscribed to the term deposit (“yes” or “no”), and this is the outcome variable we aim to predict.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bank_marketing_dataset)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 45,211
Columns: 17
$ age       &lt;int&gt; 58, 44, 33, 47, 33, 35, 28, 42, 58, 43, 41, 29, 53, 58, 57, …
$ job       &lt;fct&gt; management, technician, entrepreneur, blue-collar, unknown, …
$ marital   &lt;fct&gt; married, single, married, married, single, married, single, …
$ education &lt;fct&gt; tertiary, secondary, secondary, unknown, unknown, tertiary, …
$ default   &lt;fct&gt; no, no, no, no, no, no, no, yes, no, no, no, no, no, no, no,…
$ balance   &lt;int&gt; 2143, 29, 2, 1506, 1, 231, 447, 2, 121, 593, 270, 390, 6, 71…
$ housing   &lt;fct&gt; yes, yes, yes, yes, no, yes, yes, yes, yes, yes, yes, yes, y…
$ loan      &lt;fct&gt; no, no, yes, no, no, no, yes, no, no, no, no, no, no, no, no…
$ contact   &lt;fct&gt; unknown, unknown, unknown, unknown, unknown, unknown, unknow…
$ day       &lt;int&gt; 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, …
$ month     &lt;fct&gt; may, may, may, may, may, may, may, may, may, may, may, may, …
$ duration  &lt;int&gt; 261, 151, 76, 92, 198, 139, 217, 380, 50, 55, 222, 137, 517,…
$ campaign  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ pdays     &lt;int&gt; -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, …
$ previous  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ poutcome  &lt;fct&gt; unknown, unknown, unknown, unknown, unknown, unknown, unknow…
$ y         &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, …</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Statistical learning is a broad field concerned with understanding the relationship between a set of independent variables and dependent variable. The central question in statistical learning is always the same: <em>given what we know about a person, an observation, or a case through its predictor values, what can we say about the response?</em> The methods we use to answer this question fall into two major families, and the distinction between them depends entirely on the nature of the response variable.</p>
<p>When the response variable is quantitative, linear regression, covered in the earlier chapter, is the most classical tool for this kind of problem. It fits a model that predicts a numerical outcome as a linear combination of the independent variables, and the dependent variable is a number that can, in principle, take any value on the real number line. However, in a great many research situations the dependent variable is not quantitative but qualitative. A qualitative independent variable, also called a <strong>categorical variable</strong>, takes on values from a finite, unordered set of categories. For instance, a medical diagnosis might be “disease present” or “disease absent”. A survey respondent might identify as “satisfied”, “neutral”, or “dissatisfied”. A voter might choose among several political parties. In all of these situations, the response is not a number on a scale but a label indicating membership in a group. The task of predicting which category a new observation belongs to is what we call <strong>classification</strong>, and the methods designed for this task are called <strong>classifiers</strong>.</p>
<p>Classification therefore occupies a position within statistical learning that is parallel to regression. If regression answers the question “how much” then classification answers the question “which one”. Both regression and classification are forms of supervised learning, meaning that we have a training dataset in which both the predictors and the true response are known, and we use this dataset to build a model that can make predictions for new observations whose response we do not yet know. The difference is simply in the type of response we are trying to predict.</p>
<p>Imagine that our response variable has two categories, which we code numerically as 0 and 1. For example, within the data on heart disease , we might code “No disease” as 0 and “Disease present” as 1. One might think that we could simply fit a linear regression model with this 0/1 variable as the response, and then use the fitted values as predicted probabilities. If the model predicts a value close to 1 for a given patient, we would classify that patient as having heart disease, and if it predicts a value close to 0, we would classify the patient as healthy. The problem with this approach is that linear regression does not know that the response is a probability. A linear regression model produces fitted values by computing a linear combination of the predictors, and there is nothing in the mathematics of linear regression that constrains these fitted values to fall between 0 and 1. In practice, for some combinations of predictor values, the model will produce predictions that are less than 0 or greater than 1. These values cannot be interpreted as probabilities, and they make no logical sense in the context of classification.</p>
<p>The situation becomes even more problematic when the response variable has more than two categories. Suppose we are predicting a patient’s diagnosis and the possible outcomes are “mild condition”, “moderate condition”, and “severe condition”. To use linear regression, we would need to assign numerical codes to these categories - say 1, 2, and 3. But this coding implies that the difference between mild and moderate is the same as the difference between moderate and severe, and it implies a specific ordering. If we had instead used the codes 1, 2, and 4, the model would produce different results, even though the underlying categories have not changed. For a truly nominal variable with no natural ordering - say, three types of chest pain - any numerical coding would impose a structure that simply does not exist in the data. This is a fundamental flaw that cannot be fixed by choosing a clever coding scheme.</p>
<p>Classification methods avoid these problems entirely. Logistic regression, for example, models the probability of belonging to a particular class using a mathematical function - the logistic function - that is guaranteed to produce values between 0 and 1, no matter what values the predictors take. Discriminant analysis methods approach the problem from a different angle by modelling the distribution of the predictors within each class and then computing class probabilities using Bayes’ theorem. In both cases, the output of the model is a set of well-defined probabilities that sum to one across the possible classes, and the final classification is made by assigning each observation to the class with the highest estimated probability.</p>
<p>Our bank marketing dataset provides a perfect illustration of a classification problem. We have 4,521 individuals, and for each individual we have recorded 16 predictor variables that capture various aspects of their demographic profile, financial situation, and interactions with the marketing campaign. The response variable is whether or not the client subscribed to a term deposit, recorded as a binary outcome: “no” for clients who did not subscribe and “yes” for those who did. The classification task here is straightforward to state: given the 16 demographic, financial, and campaign-related measurements for a new client, we want to predict whether that client will subscribe to the term deposit or not. But although the question is simple, the methodology must be chosen carefully. We need a method that will estimate the probability that a given client belongs to the “yes” group versus the “no” group, and we need to evaluate how accurately that method performs so that we can trust its predictions in a marketing, business, or social research context.</p>
<p>In practice, we would proceed by first splitting the data or using resampling methods to assess how well our chosen classifier generalises to new observations. We would fit the classification model on a training portion of the data, obtain predicted class probabilities for each observation in the test portion, assign each observation to the class with the highest probability, and then evaluate performance using tools such as the confusion matrix and the ROC curve. We might try several different classification methods and compare their performance to determine which one is most appropriate for this particular dataset.</p>
<p>There are more classification methods and the field of classification is rich and rapidly evolving. However, the five methods are among the most widely used and foundational techniques in the social sciences, providing a solid starting point for understanding the principles of classification:</p>
<ul>
<li><p><strong>Logistic regression</strong> is the most widely used classification method in the social sciences conceptually close to linear regression. It directly models the probability that the response belongs to a particular class by applying the logistic function to a linear combination of the predictors. The result is a model in which the log-odds of belonging to one class versus the other is a linear function of the predictors. The coefficients are estimated using maximum likelihood, and they can be interpreted in terms of how each predictor affects the odds of the outcome.</p></li>
<li><p><strong>Linear discriminant analysis</strong> (LDA) takes a different approach. Instead of modelling the probability of class membership directly, it models the distribution of the predictor variables within each class. Specifically, it assumes that the predictors follow a multivariate normal distribution within each class and that all classes share the same covariance matrix. Using Bayes’ theorem, it then computes the posterior probability that a new observation belongs to each class. Because of the shared covariance assumption, the decision boundaries between classes are linear. LDA is particularly useful when the classes are well separated and when the normality assumption is approximately met.</p></li>
<li><p><strong>Quadratic discriminant analysis</strong> (QDA) is a generalisation of LDA that relaxes the shared covariance assumption. Each class is allowed to have its own covariance matrix, which means the decision boundaries between classes can be curved rather than straight. This gives QDA more flexibility to capture complex patterns in the data, but it also requires estimating more parameters, which means it needs more data to perform well and is more prone to overfitting when the sample size is small.</p></li>
<li><p><strong>Naive Bayes</strong> is another Bayes’ theorem-based method, but it makes a different simplifying assumption: it assumes that the independent variables are independent of each other within each class. This assumption is almost never literally true, but it has the enormous practical advantage of reducing the number of parameters that must be estimated. Instead of estimating a full covariance matrix, naive Bayes estimates only the marginal distribution of each predictor within each class. This makes it very efficient and particularly useful when the number of predictors is large relative to the number of observations.</p></li>
<li><p><strong>K-nearest neighbours</strong> (KNN) is a non-parametric method that makes no assumptions about the form of the decision boundary or the distribution of the predictors. To classify a new observation, it simply looks at the K observations in the training data that are most similar to the new observation (in terms of their predictor values) and assigns the new observation to the most common class among those neighbours. The method is intuitive and highly flexible, but its performance depends heavily on the choice of K and on the scale of the predictor variables.</p></li>
</ul>
<p>While these five methods form the core of the classification, the field of classification is much broader, and it is useful to be aware of some other important approaches. Decision trees classify observations by recursively splitting the predictor space into regions based on simple rules applied to individual predictors. The result is an intuitive tree-like structure where each internal node represents a test on a predictor, each branch represents an outcome of that test, and each leaf represents a class prediction. Decision trees are easy to interpret but can be unstable and prone to overfitting. Random forests and boosting are ensemble methods that improve on single decision trees by combining many trees together. Random forests build a large number of trees on random subsets of the data and predictors, and then aggregate their predictions by majority vote. Boosting builds trees sequentially, with each new tree focusing on the observations that the previous trees misclassified. Both methods are among the most powerful general-purpose classifiers available. Support vector machines (SVMs) construct a decision boundary by finding the hyperplane that maximises the margin between classes. They can be extended to handle non-linear boundaries through the use of kernel functions. SVMs are particularly effective in high-dimensional settings. Neural networks and deep learning are highly flexible models that learn complex, non-linear relationships between predictors and the response through layers of interconnected nodes. They are the foundation of modern machine learning and are particularly powerful for tasks involving images, text, and other unstructured data, but they can also be applied to structured datasets like ours. Each of these methods has its strengths, weaknesses, and assumptions, and part of the skill of statistical learning is knowing which method is appropriate for a given problem.</p>
<section id="logistic-regression" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">1</span> Logistic regression</h2>
<p><strong>Logistic regression</strong> is the most widely used classification method in the social sciences, and for good reason. It is a method that allows us to model the relationship between a set of independent variables and a binary categorical dependent variable - that is, a response variable that takes one of two possible values. In our bank marketing example, the response variable is whether a client subscribed to a term deposit or did not, and the predictors include demographic characteristics like age and education, financial indicators like account balance, and campaign-related variables like the duration of the last phone call.</p>
<p>The fundamental idea behind logistic regression is that rather than trying to predict the category itself directly, we instead model the probability that an observation belongs to a particular category. Specifically, we model the probability that the response variable equals “yes” given the values of the predictors. Once we have estimated this probability, classification becomes straightforward: if the estimated probability is above a certain threshold (typically 0.5), we classify the observation as “yes,” and if it is below that threshold, we classify it as “no.”</p>
<p>What makes logistic regression different from linear regression is the way it connects the predictors to the response. In linear regression, we model the expected value of a continuous response as a linear combination of the predictors, and the predicted values can range from negative infinity to positive infinity. But when the response is a probability, this is not acceptable - probabilities must lie between 0 and 1. Logistic regression solves this problem by using a special mathematical function, the <strong>logistic function</strong>, to transform the linear combination of predictors into a value that is guaranteed to fall within the interval from 0 to 1. This is the core innovation that makes logistic regression work.</p>
<p>To appreciate why the logistic function is necessary, let us first consider what happens if we naively model the probability of subscription as a linear function of a predictor. Suppose we use only one predictor, the duration of the last phone call. A linear model would look like this: the probability that a client subscribes equals some intercept plus a slope coefficient multiplied by duration. The problem is immediately apparent - for very short calls, this model might predict negative probabilities, and for very long calls, it might predict probabilities greater than one. Neither of these outcomes makes any sense.</p>
<p>The <strong>logistic function</strong> provides an elegant solution. Instead of modelling the probability as a straight line, we model it as a curve that is shaped like an elongated S. The mathematical form of the logistic function is as follows: the probability that the response equals “yes” given a predictor <span class="math inline">\(X\)</span> is equal to the exponential of the linear combination divided by one plus that same exponential. Written symbolically, this is:</p>
<p><span class="math display">\[
p(X) = \frac{e^{\beta_0 + \beta_1X}}{1 + e^{\beta_0 + \beta_1X}}
\]</span></p>
<p>This function has a very important property: no matter what values the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> take, and no matter what value <span class="math inline">\(X\)</span> takes, the output of the logistic function is always between 0 and 1. When the linear combination <span class="math inline">\(\beta_0 + \beta_1X\)</span> is a very large positive number, the exponential dominates and the function approaches 1. When the linear combination is a very large negative number, the exponential approaches 0 and the function approaches 0. When the linear combination equals 0, the function returns exactly 0.5. This S-shaped curve therefore provides a natural and mathematically well-behaved way to model probabilities.</p>
<p>To understand the coefficients of a logistic regression model, we need to introduce two related concepts: the odds and the log-odds. The <strong>odds of an event</strong> are defined as the probability that the event occurs divided by the probability that it does not occur. If the probability that a client subscribes is <span class="math inline">\(p\)</span>, then the odds of subscription are <span class="math inline">\(p / (1 - p)\)</span>. Odds are a familiar concept in everyday language - when we say that the odds of something are 3 to 1, we mean that the event is three times more likely to happen than not to happen. Unlike probabilities, which are bounded between 0 and 1, odds can range from 0 to positive infinity. An odds of 1 means the event is equally likely to occur or not occur; an odds greater than 1 means the event is more likely than not; and an odds less than 1 means the event is less likely than not.</p>
<p>Now, if we take the logistic model and rearrange it algebraically, we can show that the odds are equal to the exponential of the linear combination:</p>
<p><span class="math display">\[
\frac{p(X)}{1 − p(X)} = e^{\beta_0 + \beta_1X}
\]</span></p>
<p>If we then take the natural logarithm of both sides, we get:</p>
<p><span class="math display">\[
\log\left(\frac{p(X)}{1 − p(X)}\right) = \beta_0 + \beta_1X
\]</span></p>
<p>The left-hand side of this equation - the logarithm of the odds - is called the <strong>log-odds</strong> or, equivalently, the logit. This is an extremely important result because it tells us that in a logistic regression model, the log-odds of the response is a linear function of the predictors. This is why the method is called logistic regression: the logit is linear in the predictors, just as the response itself is linear in the predictors in ordinary linear regression.</p>
<p>The practical interpretation of the slope coefficient <span class="math inline">\(\beta_1\)</span> is as follows: a one-unit increase in the predictor <span class="math inline">\(X\)</span> is associated with a change of <span class="math inline">\(\beta_1\)</span> in the log-odds of the response. Equivalently, a one-unit increase in <span class="math inline">\(X\)</span> multiplies the odds by a factor of <span class="math inline">\(e^\beta_1\)</span>. This multiplicative interpretation of the coefficients in terms of odds ratios is central to how logistic regression results are reported and interpreted in the social sciences.</p>
<p>It is important to note that although the logit is linear in the predictors, the probability itself is not. The relationship between a predictor and the probability of the outcome is always non-linear and S-shaped. This means that the effect of a one-unit increase in a predictor on the probability depends on the current value of that predictor. Near the extremes of the probability scale (close to 0 or close to 1), changes in the predictor have relatively little effect on the probability, while near the middle of the scale (around 0.5), the same change in the predictor has a much larger effect.</p>
<p>Let us now fit a simple logistic regression model using the <code>bank_dataset</code>, predicting subscription to a term deposit based solely on the duration of the last phone call. In R, logistic regression is fitted using the <code>glm()</code> function with the argument <code>family = binomial</code>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Example: Simple Logistic Regression">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example: Simple Logistic Regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>glm()</code> function stands for generalised linear model, and by specifying <code>family = binomial</code>, we tell R that we want to fit a logistic regression. The formula <code>y ~ duration</code> specifies that we are modelling the response variable <code>y</code> as a function of the single predictor <code>duration</code>. When you run this code and call <code>summary()</code>, R will display the estimated coefficients, their standard errors, z-values, and p-values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>logistic_simple <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> duration,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bank_marketing_dataset,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ duration, family = binomial, data = bank_marketing_dataset)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.193e+00  2.613e-02 -122.19   &lt;2e-16 ***
duration     3.529e-03  5.482e-05   64.38   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 32631  on 45210  degrees of freedom
Residual deviance: 27502  on 45209  degrees of freedom
AIC: 27506

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>The most important part of the output is the coefficients table, which contains the estimated parameters of the logistic regression model.</p>
<p>The intercept is estimated as -3.193. In a logistic regression, the intercept represents the estimated log-odds of the response being “yes” when all predictors are equal to zero. In our case, this means the estimated log-odds of a client subscribing to a term deposit when the duration of the last phone call is zero seconds. A log-odds of -3.193 is a very large negative number, which tells us that when the call duration is zero, the model estimates an extremely low probability of subscription. We can convert this log-odds to a probability using the logistic function: <span class="math inline">\(p = \frac{e^{-3.193}}{1 + e^{-3.193}}\)</span>, which equals approximately 0.039, or about 3.9%. This makes intuitive sense - if the bank did not speak with the client at all, we would expect almost no chance of subscription.</p>
<p>The coefficient for duration is estimated as 0.003529. This tells us that for each additional second of call duration, the log-odds of subscribing to the term deposit increase by 0.003529. While this number may seem very small, remember that duration is measured in seconds, and phone calls typically last hundreds of seconds. Over the course of a call that lasts several minutes, the cumulative effect on the log-odds becomes substantial. To interpret this coefficient in terms of odds rather than log-odds, we exponentiate it: <span class="math inline">\(e^{0.003529} \approx 1.00353\)</span>. This means that each additional second of call duration multiplies the odds of subscription by a factor of approximately 1.0035, which is a 0.35% increase in the odds per second. If we think in terms of minutes rather than seconds, a one-minute increase (60 seconds) multiplies the odds by <span class="math inline">\(e^{0.003529 × 60} \approx e^{0.2117} \approx 1.236\)</span>, which represents a roughly 23.6% increase in the odds of subscription for each additional minute of conversation. This is a meaningful and practically significant effect - longer conversations with clients are associated with substantially higher odds of them subscribing to the term deposit.</p>
<p>The standard error for the intercept is 0.02613 and for duration it is 0.00005482. Standard errors measure the uncertainty in the coefficient estimates. Smaller standard errors indicate more precise estimates. In our case, both standard errors are very small relative to the coefficient estimates, which reflects the fact that we have a large dataset (45,211 observations) and therefore a great deal of information for estimating the parameters.</p>
<p>The z-value is computed by dividing each estimated coefficient by its standard error. For the intercept, <span class="math inline">\(z = -3.193 / 0.02613 = -122.19\)</span>. For duration, <span class="math inline">\(z = 0.003529 / 0.00005482 = 64.38\)</span>. The z-value plays the same role in logistic regression that the t-statistic plays in linear regression - it measures how many standard errors the estimated coefficient is from zero. Large absolute z-values indicate strong evidence that the true coefficient is not zero.</p>
<p>The p-value for each coefficient tests the null hypothesis that the true coefficient equals zero, meaning that the predictor has no effect on the log-odds of the response. Both p-values in our output are reported as less than <span class="math inline">\(2 \times 10^{-16}\)</span>. This means that the evidence against the null hypothesis is overwhelming - both the intercept and the duration coefficient are extremely statistically significant. The three asterisks next to each p-value confirm this, as they indicate significance at the 0.001 level, which is the most stringent threshold shown in the significance codes. For the duration predictor specifically, the tiny p-value tells us that there is an extremely strong statistical association between the length of the phone call and the probability of subscribing to the term deposit. This should not be surprising - a longer conversation gives the bank representative more time to explain the product, answer questions, and persuade the client.</p>
<p>Below the coefficients table, R reports two measures of model fit called deviances.</p>
<p>The null deviance measures how well the response variable is predicted by a model that includes only the intercept and no predictors. It is analogous to the total sum of squares in linear regression. The degrees of freedom for the null deviance equal the number of observations minus one (45,211 - 1 = 45,210). The null deviance represents the worst-case baseline - it tells us how poorly we predict if we ignore all predictor information and simply estimate the overall probability of subscription.</p>
<p>The residual deviance measures how well the response is predicted by the model that includes the predictor duration. The degrees of freedom are reduced by one (because we have estimated one additional parameter beyond the intercept), giving 45,209. The residual deviance is substantially lower than the null deviance, which tells us that adding duration to the model meaningfully improves the fit. The reduction in deviance from 32,631 to 27,502 - a drop of 5,129 - represents the improvement in explanatory power gained by including call duration as a predictor. This difference approximately follows a chi-squared distribution with one degree of freedom under the null hypothesis that duration has no effect, and a drop of 5,129 is extraordinarily large, confirming what the p-value already told us.</p>
<p>The AIC, or Akaike Information Criterion, is a measure of model quality that balances goodness of fit against model complexity. It is calculated as the residual deviance plus twice the number of estimated parameters. In our case, we estimated two parameters (the intercept and the duration coefficient), so <span class="math inline">\(AIC = 27,502 + 2 \times 2 = 27,506\)</span>. The AIC is not interpretable in absolute terms - it only becomes useful when comparing two or more models fitted to the same data. A lower AIC indicates a better model, taking into account both how well the model fits and how many parameters it uses. We will use the AIC later when comparing the simple model to the multiple logistic regression model.</p>
<p>Number of fisher scoring iterations tells us that the iterative algorithm used to maximise the likelihood function converged in 5 iterations. Fisher scoring is the numerical optimisation method that R uses internally to find the maximum likelihood estimates of the logistic regression coefficients. The fact that convergence occurred in only 5 iterations tells us that the estimation process was straightforward and that there were no numerical difficulties. If this number were very large or if R reported that the algorithm did not converge, it would be a sign of potential problems with the model, such as perfect separation of the classes.</p>
</div>
</div>
</div>
<p>In linear regression, the coefficients are estimated by the method of least squares, which finds the values of the coefficients that minimise the sum of squared differences between the observed and predicted values. In logistic regression, a different estimation method is used: <strong>maximum likelihood estimation</strong>. The intuition behind maximum likelihood is elegant. We want to find the values of the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that make the observed data as probable as possible. For each observation in our dataset, the model gives us a predicted probability that the client subscribes. For clients who actually did subscribe, we want this predicted probability to be high. For clients who did not subscribe, we want this predicted probability to be low (or equivalently, we want the predicted probability of not subscribing to be high). The likelihood function captures this idea formally: it is the product of the predicted probabilities for all the observations, where for each observation we use the predicted probability of the outcome that actually occurred.</p>
<p><strong>Maximum likelihood estimation</strong> finds the values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that maximise this likelihood function. In practice, because working with products of many small probabilities is numerically inconvenient, we work with the logarithm of the likelihood - the <strong>log-likelihood</strong> - and maximise that instead. The maximisation is performed using an iterative numerical algorithm (typically iteratively reweighted least squares), which is handled automatically by the <code>glm()</code> function in R.</p>
<p>The key output of the estimation process is the set of estimated coefficients, along with their standard errors. The standard errors measure the uncertainty in the coefficient estimates, and they are used to construct confidence intervals and hypothesis tests. The z-statistic reported in the summary output is computed by dividing each estimated coefficient by its standard error, and the associated p-value tests the null hypothesis that the true coefficient is equal to zero - that is, that the predictor has no effect on the log-odds of the response.</p>
<p>Once we have fitted a logistic regression model, we can use it to make predictions for new observations. In R, the <code>predict()</code> function is used for this purpose. By default, <code>predict()</code> applied to a glm object returns the predicted values on the scale of the linear predictor - that is, the predicted log-odds. To obtain predicted probabilities, we must specify <code>type = "response"</code>.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Example: Making Predictions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example: Making Predictions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>predicted_probabilities <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  logistic_simple,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predicted_probabilities)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
0.09352110 0.06539995 0.05096579 0.05376734 0.07629941 0.06285851 </code></pre>
</div>
</div>
<p>This code produces the estimated probability of subscribing to the term deposit for each client in the dataset. Each value will be a number between 0 and 1. To convert these probabilities into class predictions, we apply a threshold - typically 0.5.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>predicted_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probabilities <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"yes"</span>, <span class="st">"no"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> predicted_class, <span class="at">Actual =</span> bank_marketing_dataset<span class="sc">$</span>y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted    no   yes
      no  39351  4465
      yes   571   824</code></pre>
</div>
</div>
<p>This produces a confusion matrix, which is a cross-tabulation of the predicted class labels against the actual class labels. The confusion matrix tells us how many clients were correctly classified and how many were misclassified. We will explore the confusion matrix and related performance metrics in more detail later, but for now it is important to understand that this is the basic workflow of logistic regression: fit the model, extract predicted probabilities, apply a threshold, and evaluate the results.</p>
<p>We can also make predictions for specific hypothetical clients. Suppose we want to know the predicted probability of subscription for a client whose last call lasted 300 seconds:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>new_client <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">duration =</span> <span class="dv">300</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logistic_simple, <span class="at">newdata =</span> new_client, <span class="at">type =</span> <span class="st">"response"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1 
0.1058604 </code></pre>
</div>
</div>
<p>This will return a single probability representing the model’s estimate of how likely it is that a client with a 300-second phone call will subscribe to the term deposit.</p>
</div>
</div>
</div>
<section id="multiple-logistic-regression" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="multiple-logistic-regression"><span class="header-section-number">1.1</span> Multiple Logistic Regression</h3>
<p>In practice, we almost never rely on a single predictor. Multiple logistic regression extends the simple logistic regression model to include several predictors simultaneously. The logistic model generalises naturally: the log-odds of the response is modelled as a linear combination of all the predictors. If we have p predictors, the model is:</p>
<p><span class="math display">\[
log(\frac{p(X)}{1 - p(X)}) = \beta_0 + \beta_0X_1 + \beta_2X_2 + ... + \beta_pX_p
\]</span></p>
<p>Each coefficient represents the change in the log-odds of the response associated with a one-unit increase in predictor, holding all other predictors constant. This “holding all other predictors constant” interpretation is exactly the same as in multiple linear regression, and it is one of the most important aspects of the model for social science research, because it allows us to isolate the effect of each predictor after controlling for the others.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Example: Multiple Logistic Regression">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example: Multiple Logistic Regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In this model, we are predicting subscription using a rich set of demographic, financial, and campaign-related variables. Notice that several of these predictors are categorical (such as <code>job</code>, <code>marital</code>, <code>education</code>, <code>housing</code>, <code>loan</code>, <code>contact</code>, and <code>poutcome</code>), and R automatically creates dummy variables for each category, choosing one category as the reference level.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>logistic_multiple <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> age <span class="sc">+</span> job <span class="sc">+</span> marital <span class="sc">+</span> education <span class="sc">+</span> balance <span class="sc">+</span> housing <span class="sc">+</span> loan <span class="sc">+</span> contact <span class="sc">+</span> duration <span class="sc">+</span> campaign <span class="sc">+</span> poutcome,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bank_marketing_dataset,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ age + job + marital + education + balance + 
    housing + loan + contact + duration + campaign + poutcome, 
    family = binomial, data = bank_marketing_dataset)

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)        -2.499e+00  1.493e-01 -16.739  &lt; 2e-16 ***
age                 1.558e-03  2.147e-03   0.725 0.468188    
jobblue-collar     -3.946e-01  7.107e-02  -5.553 2.81e-08 ***
jobentrepreneur    -4.920e-01  1.232e-01  -3.995 6.48e-05 ***
jobhousemaid       -5.304e-01  1.325e-01  -4.003 6.25e-05 ***
jobmanagement      -2.295e-01  7.152e-02  -3.209 0.001334 ** 
jobretired          3.385e-01  9.367e-02   3.614 0.000301 ***
jobself-employed   -3.856e-01  1.092e-01  -3.531 0.000415 ***
jobservices        -3.128e-01  8.217e-02  -3.806 0.000141 ***
jobstudent          5.041e-01  1.059e-01   4.761 1.93e-06 ***
jobtechnician      -2.745e-01  6.698e-02  -4.098 4.16e-05 ***
jobunemployed      -2.214e-01  1.091e-01  -2.029 0.042418 *  
jobunknown         -3.374e-01  2.294e-01  -1.471 0.141416    
maritalmarried     -1.576e-01  5.742e-02  -2.745 0.006047 ** 
maritalsingle       1.617e-01  6.540e-02   2.472 0.013422 *  
educationsecondary  1.650e-01  6.331e-02   2.607 0.009143 ** 
educationtertiary   4.028e-01  7.345e-02   5.484 4.16e-08 ***
educationunknown    2.690e-01  1.012e-01   2.657 0.007873 ** 
balance             1.780e-05  4.850e-06   3.671 0.000242 ***
housingyes         -7.643e-01  3.922e-02 -19.485  &lt; 2e-16 ***
loanyes            -5.673e-01  5.805e-02  -9.772  &lt; 2e-16 ***
contacttelephone   -7.945e-02  7.229e-02  -1.099 0.271702    
contactunknown     -1.157e+00  5.776e-02 -20.024  &lt; 2e-16 ***
duration            4.054e-03  6.274e-05  64.627  &lt; 2e-16 ***
campaign           -1.091e-01  9.894e-03 -11.022  &lt; 2e-16 ***
poutcomeother       2.571e-01  8.636e-02   2.977 0.002911 ** 
poutcomesuccess     2.288e+00  7.648e-02  29.917  &lt; 2e-16 ***
poutcomeunknown    -3.194e-01  5.438e-02  -5.873 4.29e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 32631  on 45210  degrees of freedom
Residual deviance: 22609  on 45183  degrees of freedom
AIC: 22665

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>We can also compute predicted probabilities and class predictions from the multiple model in the same way as before:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>predicted_probs_multiple <span class="ot">&lt;-</span> <span class="fu">predict</span>(logistic_multiple, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>predicted_class_multiple <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probs_multiple <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"yes"</span>, <span class="st">"no"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> predicted_class_multiple, <span class="at">Actual =</span> bank_marketing_dataset<span class="sc">$</span>y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted    no   yes
      no  39009  3580
      yes   913  1709</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>An important point to emphasise is that the coefficients in a multiple logistic regression model can differ substantially from those in a simple logistic regression model using the same predictor. This is because the multiple model controls for confounding - the relationships among the predictors themselves. A predictor that appears highly significant on its own may become non-significant once other variables are included in the model, or vice versa. This is a well-known phenomenon in regression analysis and underscores the importance of fitting models with multiple predictors rather than drawing conclusions from a series of simple models.</p>
</section>
<section id="multinomial-logistic-regression" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="multinomial-logistic-regression"><span class="header-section-number">1.2</span> Multinomial Logistic Regression</h3>
<p>Everything we have discussed so far applies to the case where the response variable has exactly two categories. But what happens when the response variable has three or more categories? This is where multinomial logistic regression comes in. <strong>Multinomial logistic regression</strong> is a generalisation of binary logistic regression to situations where the response variable has K categories, where K is greater than two. The idea is to choose one of the K categories as a baseline or reference category, and then fit <span class="math inline">\(K - 1\)</span> separate logistic regression equations, each of which models the log-odds of being in a particular category relative to the reference category.</p>
<p>For example, suppose we had a response variable with three categories: “subscribed to product A”, “subscribed to product B”, and “did not subscribe”. If we choose “did not subscribe” as the baseline, then we would fit two logistic equations: one for the log-odds of subscribing to product A versus not subscribing, and another for the log-odds of subscribing to product B versus not subscribing. Each equation has its own set of coefficients, and the predicted probability of each outcome is computed using a generalisation of the logistic function called the <strong>softmax function</strong>.</p>
<p>The softmax function ensures that the predicted probabilities for all K categories sum to one for each observation. For an observation with predictor values X, the probability of belonging to class k (for <span class="math inline">\(k = 1, ..., K-1\)</span>) relative to the baseline class K is:</p>
<p><span class="math display">\[
P(Y = k | X) = \frac{e^{\beta_{k0} + \beta_{k1}X_1 + ... + \beta_{kp}X_p}}{(1 + \sum_{l=1}^{K-1} e^(\beta_{l0} + \beta_{l1}X_1 + ... + \beta_{lp}X_p))}
\]</span></p>
<p>The probability of the baseline class is:</p>
<p><span class="math display">\[
P(Y = K | X) = \frac{1}{1 + \sum_{l=1}^{K-1} e^{\beta_{l0} + \beta_{l1}X_1 + ... + \beta_{lp}X_p}}
\]</span></p>
<p>The interpretation of coefficients in multinomial logistic regression follows the same logic as in binary logistic regression, except that each coefficient refers to the effect of a predictor on the log-odds of a specific category relative to the baseline. This means that the output is more complex, but the fundamental idea remains the same.</p>
<p>In our bank dataset, the response variable <code>y</code> is binary, so we do not strictly need multinomial logistic regression. However, it is useful to see how it works in R, because many social science research questions involve multi-category outcomes. The <code>nnet</code> package in R provides the <code>multinom()</code> function for fitting multinomial logistic regression models.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled" title="Example: Multinomial Logistic Regression">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Example: Multinomial Logistic Regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In this case, because <code>y</code> has only two levels, the multinomial model will produce results that are equivalent to binary logistic regression. But if the response had three or more levels, the output would include a separate row of coefficients for each non-reference category. The <code>multinom()</code> function uses the first level of the factor as the reference category by default.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>multinomial_model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> age <span class="sc">+</span> duration <span class="sc">+</span> balance <span class="sc">+</span> education,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bank_marketing_dataset</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  8 (7 variable)
initial  value 31337.877180 
iter  10 value 13616.220902
iter  20 value 13558.490060
iter  30 value 13558.322787
iter  30 value 13558.322737
iter  30 value 13558.322627
final  value 13558.322627 
converged</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multinomial_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = y ~ age + duration + balance + education, 
    data = bank_marketing_dataset)

Coefficients:
                          Values    Std. Err.
(Intercept)        -4.155791e+00 1.604265e-04
age                 1.084171e-02 6.014300e-04
duration            3.561245e-03 5.209821e-05
balance             3.126106e-05 4.202193e-06
educationsecondary  3.442658e-01 1.849096e-02
educationtertiary   7.960673e-01 1.717328e-02
educationunknown    6.200282e-01 3.369228e-04

Residual Deviance: 27116.65 
AIC: 27130.65 </code></pre>
</div>
</div>
<p>To obtain predicted class probabilities from a multinomial model, we use:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>predicted_probs_multinomial <span class="ot">&lt;-</span> <span class="fu">predict</span>(multinomial_model, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predicted_probs_multinomial)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
0.15002211 0.05754961 0.03980927 0.06589728 0.07778505 0.07741278 </code></pre>
</div>
</div>
<p>And to obtain predicted class labels:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>predicted_class_multinomial <span class="ot">&lt;-</span> <span class="fu">predict</span>(multinomial_model, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> predicted_class_multinomial, <span class="at">Actual =</span> bank_marketing_dataset<span class="sc">$</span>y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted    no   yes
      no  39332  4426
      yes   590   863</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="generative-models-for-classification" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="generative-models-for-classification"><span class="header-section-number">2</span> Generative Models for Classification</h2>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02_linear_regression.html" class="pagination-link" aria-label="Linear Regression Model">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Regression Model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Classification"</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> ""</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="an">number-sections:</span><span class="co"> true</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="an">title-block-banner:</span><span class="co"> "#00868B"</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="an">title-block-banner-color:</span><span class="co"> "white"</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="an">crossref:</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co">  fig-title: "Figure"</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co">  tbl-title: "Table"</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/bank-full.csv"</span>, <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>y <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>y)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>job <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>job)</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>marital <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>marital)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>education <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>education)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>default <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>default)</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>housing <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>housing)</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>loan <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>loan)</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>contact <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>contact)</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>month)</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>bank_marketing_dataset<span class="sc">$</span>poutcome <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(bank_marketing_dataset<span class="sc">$</span>poutcome)</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>::: {.callout-note icon="false" collapse="true" title="Dataset: <span class="in">`bank_marketing_dataset`</span>"}</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>The <span class="in">`bank_marketing_dataset`</span> dataset is a social and behavioral dataset that seeks to capture the demographic, financial, and campaign-related factors that influence whether a bank client decides to subscribe to a term deposit following a direct marketing campaign. The fundamental research question behind this dataset is: *what characteristics of a client and of the marketing contact predict the decision to subscribe to a financial product, and how strongly does each factor contribute?* This dataset is publicly available on the <span class="co">[</span><span class="ot">UCI Machine Learning Repository</span><span class="co">](https://archive.ics.uci.edu/dataset/222/bank+marketing)</span>. The dataset contains 4,521 observations, where each observation represents one individual client contacted during a phone-based marketing campaign run by a Portuguese banking institution. For each client, 17 variables have been recorded. One of these variables is the outcome we want to predict (dependent variable), and the remaining 16 are potential predictors (independent variables). The variables are as follows:</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`age`</span> records the age of the client in years,</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`job`</span> describes the type of occupation of the client within the different categories,</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`marital`</span> records the marital status of the client, categorized as married, single, or divorced (where divorced also includes widowed),</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`education`</span> indicates the highest level of education the client has completed, with categories primary, secondary, and tertiary,</span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`default`</span> indicates whether the client has credit currently in default ("yes" or "no"),</span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`balance`</span> records the average annual balance held in the client's bank account, measured in euros,</span>
<span id="cb23-48"><a href="#cb23-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-49"><a href="#cb23-49" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`housing`</span> indicates whether the client has an active housing loan ("yes" or "no"),</span>
<span id="cb23-50"><a href="#cb23-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-51"><a href="#cb23-51" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`loan`</span> indicates whether the client has an active personal loan ("yes" or "no"),</span>
<span id="cb23-52"><a href="#cb23-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-53"><a href="#cb23-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`contact`</span> describes the type of communication channel used to contact the client, with categories cellular, telephone, and unknown,</span>
<span id="cb23-54"><a href="#cb23-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-55"><a href="#cb23-55" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`day`</span> records the day of the month on which the client was last contacted,</span>
<span id="cb23-56"><a href="#cb23-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-57"><a href="#cb23-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`month`</span> records the month of the year in which the client was last contacted,</span>
<span id="cb23-58"><a href="#cb23-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-59"><a href="#cb23-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`duration`</span> records the duration of the last contact with the client in seconds (this variable is only known after the call has ended, and therefore should be used with caution in predictive modeling),</span>
<span id="cb23-60"><a href="#cb23-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-61"><a href="#cb23-61" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`campaign`</span> records the total number of times the client was contacted during the current marketing campaign,</span>
<span id="cb23-62"><a href="#cb23-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-63"><a href="#cb23-63" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`pdays`</span> records the number of days that elapsed since the client was last contacted in a previous campaign (-1 indicates the client had not been previously contacted),</span>
<span id="cb23-64"><a href="#cb23-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-65"><a href="#cb23-65" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`previous`</span> records the total number of times the client was contacted before the current campaign,</span>
<span id="cb23-66"><a href="#cb23-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-67"><a href="#cb23-67" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`poutcome`</span> describes the outcome of the previous marketing campaign for this client, with categories success, failure, other, and unknown,</span>
<span id="cb23-68"><a href="#cb23-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-69"><a href="#cb23-69" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`y`</span> records whether the client ultimately subscribed to the term deposit ("yes" or "no"), and this is the outcome variable we aim to predict.</span>
<span id="cb23-70"><a href="#cb23-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-73"><a href="#cb23-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-74"><a href="#cb23-74" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bank_marketing_dataset)</span>
<span id="cb23-75"><a href="#cb23-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-76"><a href="#cb23-76" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb23-77"><a href="#cb23-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-78"><a href="#cb23-78" aria-hidden="true" tabindex="-1"></a>Statistical learning is a broad field concerned with understanding the relationship between a set of independent variables and dependent variable. The central question in statistical learning is always the same: *given what we know about a person, an observation, or a case through its predictor values, what can we say about the response?* The methods we use to answer this question fall into two major families, and the distinction between them depends entirely on the nature of the response variable.</span>
<span id="cb23-79"><a href="#cb23-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-80"><a href="#cb23-80" aria-hidden="true" tabindex="-1"></a>When the response variable is quantitative, linear regression, covered in the earlier chapter, is the most classical tool for this kind of problem. It fits a model that predicts a numerical outcome as a linear combination of the independent variables, and the dependent variable is a number that can, in principle, take any value on the real number line. However, in a great many research situations the dependent variable is not quantitative but qualitative. A qualitative independent variable, also called a **categorical variable**, takes on values from a finite, unordered set of categories. For instance, a medical diagnosis might be "disease present" or "disease absent". A survey respondent might identify as "satisfied", "neutral", or "dissatisfied". A voter might choose among several political parties. In all of these situations, the response is not a number on a scale but a label indicating membership in a group. The task of predicting which category a new observation belongs to is what we call **classification**, and the methods designed for this task are called **classifiers**.</span>
<span id="cb23-81"><a href="#cb23-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-82"><a href="#cb23-82" aria-hidden="true" tabindex="-1"></a>Classification therefore occupies a position within statistical learning that is parallel to regression. If regression answers the question "how much" then classification answers the question "which one". Both regression and classification are forms of supervised learning, meaning that we have a training dataset in which both the predictors and the true response are known, and we use this dataset to build a model that can make predictions for new observations whose response we do not yet know. The difference is simply in the type of response we are trying to predict.</span>
<span id="cb23-83"><a href="#cb23-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-84"><a href="#cb23-84" aria-hidden="true" tabindex="-1"></a>Imagine that our response variable has two categories, which we code numerically as 0 and 1. For example, within the data on heart disease , we might code "No disease" as 0 and "Disease present" as 1. One might think that we could simply fit a linear regression model with this 0/1 variable as the response, and then use the fitted values as predicted probabilities. If the model predicts a value close to 1 for a given patient, we would classify that patient as having heart disease, and if it predicts a value close to 0, we would classify the patient as healthy. The problem with this approach is that linear regression does not know that the response is a probability. A linear regression model produces fitted values by computing a linear combination of the predictors, and there is nothing in the mathematics of linear regression that constrains these fitted values to fall between 0 and 1. In practice, for some combinations of predictor values, the model will produce predictions that are less than 0 or greater than 1. These values cannot be interpreted as probabilities, and they make no logical sense in the context of classification.</span>
<span id="cb23-85"><a href="#cb23-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-86"><a href="#cb23-86" aria-hidden="true" tabindex="-1"></a>The situation becomes even more problematic when the response variable has more than two categories. Suppose we are predicting a patient's diagnosis and the possible outcomes are "mild condition", "moderate condition", and "severe condition". To use linear regression, we would need to assign numerical codes to these categories - say 1, 2, and 3. But this coding implies that the difference between mild and moderate is the same as the difference between moderate and severe, and it implies a specific ordering. If we had instead used the codes 1, 2, and 4, the model would produce different results, even though the underlying categories have not changed. For a truly nominal variable with no natural ordering - say, three types of chest pain - any numerical coding would impose a structure that simply does not exist in the data. This is a fundamental flaw that cannot be fixed by choosing a clever coding scheme.</span>
<span id="cb23-87"><a href="#cb23-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-88"><a href="#cb23-88" aria-hidden="true" tabindex="-1"></a>Classification methods avoid these problems entirely. Logistic regression, for example, models the probability of belonging to a particular class using a mathematical function - the logistic function - that is guaranteed to produce values between 0 and 1, no matter what values the predictors take. Discriminant analysis methods approach the problem from a different angle by modelling the distribution of the predictors within each class and then computing class probabilities using Bayes' theorem. In both cases, the output of the model is a set of well-defined probabilities that sum to one across the possible classes, and the final classification is made by assigning each observation to the class with the highest estimated probability.</span>
<span id="cb23-89"><a href="#cb23-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-90"><a href="#cb23-90" aria-hidden="true" tabindex="-1"></a>Our bank marketing dataset provides a perfect illustration of a classification problem. We have 4,521 individuals, and for each individual we have recorded 16 predictor variables that capture various aspects of their demographic profile, financial situation, and interactions with the marketing campaign. The response variable is whether or not the client subscribed to a term deposit, recorded as a binary outcome: "no" for clients who did not subscribe and "yes" for those who did. The classification task here is straightforward to state: given the 16 demographic, financial, and campaign-related measurements for a new client, we want to predict whether that client will subscribe to the term deposit or not. But although the question is simple, the methodology must be chosen carefully. We need a method that will estimate the probability that a given client belongs to the "yes" group versus the "no" group, and we need to evaluate how accurately that method performs so that we can trust its predictions in a marketing, business, or social research context.</span>
<span id="cb23-91"><a href="#cb23-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-92"><a href="#cb23-92" aria-hidden="true" tabindex="-1"></a>In practice, we would proceed by first splitting the data or using resampling methods to assess how well our chosen classifier generalises to new observations. We would fit the classification model on a training portion of the data, obtain predicted class probabilities for each observation in the test portion, assign each observation to the class with the highest probability, and then evaluate performance using tools such as the confusion matrix and the ROC curve. We might try several different classification methods and compare their performance to determine which one is most appropriate for this particular dataset.</span>
<span id="cb23-93"><a href="#cb23-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-94"><a href="#cb23-94" aria-hidden="true" tabindex="-1"></a>There are more classification methods and the field of classification is rich and rapidly evolving. However, the five methods are among the most widely used and foundational techniques in the social sciences, providing a solid starting point for understanding the principles of classification:</span>
<span id="cb23-95"><a href="#cb23-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-96"><a href="#cb23-96" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Logistic regression** is the most widely used classification method in the social sciences conceptually close to linear regression. It directly models the probability that the response belongs to a particular class by applying the logistic function to a linear combination of the predictors. The result is a model in which the log-odds of belonging to one class versus the other is a linear function of the predictors. The coefficients are estimated using maximum likelihood, and they can be interpreted in terms of how each predictor affects the odds of the outcome.</span>
<span id="cb23-97"><a href="#cb23-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-98"><a href="#cb23-98" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Linear discriminant analysis** (LDA) takes a different approach. Instead of modelling the probability of class membership directly, it models the distribution of the predictor variables within each class. Specifically, it assumes that the predictors follow a multivariate normal distribution within each class and that all classes share the same covariance matrix. Using Bayes' theorem, it then computes the posterior probability that a new observation belongs to each class. Because of the shared covariance assumption, the decision boundaries between classes are linear. LDA is particularly useful when the classes are well separated and when the normality assumption is approximately met.</span>
<span id="cb23-99"><a href="#cb23-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-100"><a href="#cb23-100" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Quadratic discriminant analysis** (QDA) is a generalisation of LDA that relaxes the shared covariance assumption. Each class is allowed to have its own covariance matrix, which means the decision boundaries between classes can be curved rather than straight. This gives QDA more flexibility to capture complex patterns in the data, but it also requires estimating more parameters, which means it needs more data to perform well and is more prone to overfitting when the sample size is small.</span>
<span id="cb23-101"><a href="#cb23-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-102"><a href="#cb23-102" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Naive Bayes** is another Bayes' theorem-based method, but it makes a different simplifying assumption: it assumes that the independent variables are independent of each other within each class. This assumption is almost never literally true, but it has the enormous practical advantage of reducing the number of parameters that must be estimated. Instead of estimating a full covariance matrix, naive Bayes estimates only the marginal distribution of each predictor within each class. This makes it very efficient and particularly useful when the number of predictors is large relative to the number of observations.</span>
<span id="cb23-103"><a href="#cb23-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-104"><a href="#cb23-104" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**K-nearest neighbours** (KNN) is a non-parametric method that makes no assumptions about the form of the decision boundary or the distribution of the predictors. To classify a new observation, it simply looks at the K observations in the training data that are most similar to the new observation (in terms of their predictor values) and assigns the new observation to the most common class among those neighbours. The method is intuitive and highly flexible, but its performance depends heavily on the choice of K and on the scale of the predictor variables.</span>
<span id="cb23-105"><a href="#cb23-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-106"><a href="#cb23-106" aria-hidden="true" tabindex="-1"></a>While these five methods form the core of the classification, the field of classification is much broader, and it is useful to be aware of some other important approaches. Decision trees classify observations by recursively splitting the predictor space into regions based on simple rules applied to individual predictors. The result is an intuitive tree-like structure where each internal node represents a test on a predictor, each branch represents an outcome of that test, and each leaf represents a class prediction. Decision trees are easy to interpret but can be unstable and prone to overfitting. Random forests and boosting are ensemble methods that improve on single decision trees by combining many trees together. Random forests build a large number of trees on random subsets of the data and predictors, and then aggregate their predictions by majority vote. Boosting builds trees sequentially, with each new tree focusing on the observations that the previous trees misclassified. Both methods are among the most powerful general-purpose classifiers available. Support vector machines (SVMs) construct a decision boundary by finding the hyperplane that maximises the margin between classes. They can be extended to handle non-linear boundaries through the use of kernel functions. SVMs are particularly effective in high-dimensional settings. Neural networks and deep learning are highly flexible models that learn complex, non-linear relationships between predictors and the response through layers of interconnected nodes. They are the foundation of modern machine learning and are particularly powerful for tasks involving images, text, and other unstructured data, but they can also be applied to structured datasets like ours. Each of these methods has its strengths, weaknesses, and assumptions, and part of the skill of statistical learning is knowing which method is appropriate for a given problem.</span>
<span id="cb23-107"><a href="#cb23-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-108"><a href="#cb23-108" aria-hidden="true" tabindex="-1"></a><span class="fu">## Logistic regression</span></span>
<span id="cb23-109"><a href="#cb23-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-110"><a href="#cb23-110" aria-hidden="true" tabindex="-1"></a>**Logistic regression** is the most widely used classification method in the social sciences, and for good reason. It is a method that allows us to model the relationship between a set of independent variables and a binary categorical dependent variable - that is, a response variable that takes one of two possible values. In our bank marketing example, the response variable is whether a client subscribed to a term deposit or did not, and the predictors include demographic characteristics like age and education, financial indicators like account balance, and campaign-related variables like the duration of the last phone call.</span>
<span id="cb23-111"><a href="#cb23-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-112"><a href="#cb23-112" aria-hidden="true" tabindex="-1"></a>The fundamental idea behind logistic regression is that rather than trying to predict the category itself directly, we instead model the probability that an observation belongs to a particular category. Specifically, we model the probability that the response variable equals "yes" given the values of the predictors. Once we have estimated this probability, classification becomes straightforward: if the estimated probability is above a certain threshold (typically 0.5), we classify the observation as "yes," and if it is below that threshold, we classify it as "no."</span>
<span id="cb23-113"><a href="#cb23-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-114"><a href="#cb23-114" aria-hidden="true" tabindex="-1"></a>What makes logistic regression different from linear regression is the way it connects the predictors to the response. In linear regression, we model the expected value of a continuous response as a linear combination of the predictors, and the predicted values can range from negative infinity to positive infinity. But when the response is a probability, this is not acceptable - probabilities must lie between 0 and 1. Logistic regression solves this problem by using a special mathematical function, the **logistic function**, to transform the linear combination of predictors into a value that is guaranteed to fall within the interval from 0 to 1. This is the core innovation that makes logistic regression work.</span>
<span id="cb23-115"><a href="#cb23-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-116"><a href="#cb23-116" aria-hidden="true" tabindex="-1"></a>To appreciate why the logistic function is necessary, let us first consider what happens if we naively model the probability of subscription as a linear function of a predictor. Suppose we use only one predictor, the duration of the last phone call. A linear model would look like this: the probability that a client subscribes equals some intercept plus a slope coefficient multiplied by duration. The problem is immediately apparent - for very short calls, this model might predict negative probabilities, and for very long calls, it might predict probabilities greater than one. Neither of these outcomes makes any sense.</span>
<span id="cb23-117"><a href="#cb23-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-118"><a href="#cb23-118" aria-hidden="true" tabindex="-1"></a>The **logistic function** provides an elegant solution. Instead of modelling the probability as a straight line, we model it as a curve that is shaped like an elongated S. The mathematical form of the logistic function is as follows: the probability that the response equals "yes" given a predictor $X$ is equal to the exponential of the linear combination divided by one plus that same exponential. Written symbolically, this is:</span>
<span id="cb23-119"><a href="#cb23-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-120"><a href="#cb23-120" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-121"><a href="#cb23-121" aria-hidden="true" tabindex="-1"></a>p(X) = \frac{e^{\beta_0 + \beta_1X}}{1 + e^{\beta_0 + \beta_1X}}</span>
<span id="cb23-122"><a href="#cb23-122" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-123"><a href="#cb23-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-124"><a href="#cb23-124" aria-hidden="true" tabindex="-1"></a>This function has a very important property: no matter what values the coefficients $\beta_0$ and $\beta_1$ take, and no matter what value $X$ takes, the output of the logistic function is always between 0 and 1. When the linear combination $\beta_0 + \beta_1X$ is a very large positive number, the exponential dominates and the function approaches 1. When the linear combination is a very large negative number, the exponential approaches 0 and the function approaches 0. When the linear combination equals 0, the function returns exactly 0.5. This S-shaped curve therefore provides a natural and mathematically well-behaved way to model probabilities.</span>
<span id="cb23-125"><a href="#cb23-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-126"><a href="#cb23-126" aria-hidden="true" tabindex="-1"></a>To understand the coefficients of a logistic regression model, we need to introduce two related concepts: the odds and the log-odds.</span>
<span id="cb23-127"><a href="#cb23-127" aria-hidden="true" tabindex="-1"></a>The **odds of an event** are defined as the probability that the event occurs divided by the probability that it does not occur. If the probability that a client subscribes is $p$, then the odds of subscription are $p / (1 - p)$. Odds are a familiar concept in everyday language - when we say that the odds of something are 3 to 1, we mean that the event is three times more likely to happen than not to happen. Unlike probabilities, which are bounded between 0 and 1, odds can range from 0 to positive infinity. An odds of 1 means the event is equally likely to occur or not occur; an odds greater than 1 means the event is more likely than not; and an odds less than 1 means the event is less likely than not.</span>
<span id="cb23-128"><a href="#cb23-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-129"><a href="#cb23-129" aria-hidden="true" tabindex="-1"></a>Now, if we take the logistic model and rearrange it algebraically, we can show that the odds are equal to the exponential of the linear combination:</span>
<span id="cb23-130"><a href="#cb23-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-131"><a href="#cb23-131" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-132"><a href="#cb23-132" aria-hidden="true" tabindex="-1"></a>\frac{p(X)}{1 − p(X)} = e^{\beta_0 + \beta_1X}</span>
<span id="cb23-133"><a href="#cb23-133" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-134"><a href="#cb23-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-135"><a href="#cb23-135" aria-hidden="true" tabindex="-1"></a>If we then take the natural logarithm of both sides, we get:</span>
<span id="cb23-136"><a href="#cb23-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-137"><a href="#cb23-137" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-138"><a href="#cb23-138" aria-hidden="true" tabindex="-1"></a>\log\left(\frac{p(X)}{1 − p(X)}\right) = \beta_0 + \beta_1X</span>
<span id="cb23-139"><a href="#cb23-139" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-140"><a href="#cb23-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-141"><a href="#cb23-141" aria-hidden="true" tabindex="-1"></a>The left-hand side of this equation - the logarithm of the odds - is called the **log-odds** or, equivalently, the logit. This is an extremely important result because it tells us that in a logistic regression model, the log-odds of the response is a linear function of the predictors. This is why the method is called logistic regression: the logit is linear in the predictors, just as the response itself is linear in the predictors in ordinary linear regression.</span>
<span id="cb23-142"><a href="#cb23-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-143"><a href="#cb23-143" aria-hidden="true" tabindex="-1"></a>The practical interpretation of the slope coefficient $\beta_1$ is as follows: a one-unit increase in the predictor $X$ is associated with a change of $\beta_1$ in the log-odds of the response. Equivalently, a one-unit increase in $X$ multiplies the odds by a factor of $e^\beta_1$. This multiplicative interpretation of the coefficients in terms of odds ratios is central to how logistic regression results are reported and interpreted in the social sciences.</span>
<span id="cb23-144"><a href="#cb23-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-145"><a href="#cb23-145" aria-hidden="true" tabindex="-1"></a>It is important to note that although the logit is linear in the predictors, the probability itself is not. The relationship between a predictor and the probability of the outcome is always non-linear and S-shaped. This means that the effect of a one-unit increase in a predictor on the probability depends on the current value of that predictor. Near the extremes of the probability scale (close to 0 or close to 1), changes in the predictor have relatively little effect on the probability, while near the middle of the scale (around 0.5), the same change in the predictor has a much larger effect.</span>
<span id="cb23-146"><a href="#cb23-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-147"><a href="#cb23-147" aria-hidden="true" tabindex="-1"></a>Let us now fit a simple logistic regression model using the <span class="in">`bank_dataset`</span>, predicting subscription to a term deposit based solely on the duration of the last phone call. In R, logistic regression is fitted using the <span class="in">`glm()`</span> function with the argument <span class="in">`family = binomial`</span>.</span>
<span id="cb23-148"><a href="#cb23-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-149"><a href="#cb23-149" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip icon="false" collapse="true" title="Example: Simple Logistic Regression"}</span>
<span id="cb23-150"><a href="#cb23-150" aria-hidden="true" tabindex="-1"></a>The <span class="in">`glm()`</span> function stands for generalised linear model, and by specifying <span class="in">`family = binomial`</span>, we tell R that we want to fit a logistic regression. The formula <span class="in">`y ~ duration`</span> specifies that we are modelling the response variable <span class="in">`y`</span> as a function of the single predictor <span class="in">`duration`</span>. When you run this code and call <span class="in">`summary()`</span>, R will display the estimated coefficients, their standard errors, z-values, and p-values.</span>
<span id="cb23-151"><a href="#cb23-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-154"><a href="#cb23-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-155"><a href="#cb23-155" aria-hidden="true" tabindex="-1"></a>logistic_simple <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb23-156"><a href="#cb23-156" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> duration,</span>
<span id="cb23-157"><a href="#cb23-157" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bank_marketing_dataset,</span>
<span id="cb23-158"><a href="#cb23-158" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb23-159"><a href="#cb23-159" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-160"><a href="#cb23-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-161"><a href="#cb23-161" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_simple)</span>
<span id="cb23-162"><a href="#cb23-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-163"><a href="#cb23-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-164"><a href="#cb23-164" aria-hidden="true" tabindex="-1"></a>The most important part of the output is the coefficients table, which contains the estimated parameters of the logistic regression model.</span>
<span id="cb23-165"><a href="#cb23-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-166"><a href="#cb23-166" aria-hidden="true" tabindex="-1"></a>The intercept is estimated as -3.193. In a logistic regression, the intercept represents the estimated log-odds of the response being "yes" when all predictors are equal to zero. In our case, this means the estimated log-odds of a client subscribing to a term deposit when the duration of the last phone call is zero seconds. A log-odds of -3.193 is a very large negative number, which tells us that when the call duration is zero, the model estimates an extremely low probability of subscription. We can convert this log-odds to a probability using the logistic function: $p = \frac{e^{-3.193}}{1 + e^{-3.193}}$, which equals approximately 0.039, or about 3.9%. This makes intuitive sense - if the bank did not speak with the client at all, we would expect almost no chance of subscription.</span>
<span id="cb23-167"><a href="#cb23-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-168"><a href="#cb23-168" aria-hidden="true" tabindex="-1"></a>The coefficient for duration is estimated as 0.003529. This tells us that for each additional second of call duration, the log-odds of subscribing to the term deposit increase by 0.003529. While this number may seem very small, remember that duration is measured in seconds, and phone calls typically last hundreds of seconds. Over the course of a call that lasts several minutes, the cumulative effect on the log-odds becomes substantial. To interpret this coefficient in terms of odds rather than log-odds, we exponentiate it: $e^{0.003529} \approx 1.00353$. This means that each additional second of call duration multiplies the odds of subscription by a factor of approximately 1.0035, which is a 0.35% increase in the odds per second. If we think in terms of minutes rather than seconds, a one-minute increase (60 seconds) multiplies the odds by $e^{0.003529 × 60} \approx e^{0.2117} \approx 1.236$, which represents a roughly 23.6% increase in the odds of subscription for each additional minute of conversation. This is a meaningful and practically significant effect - longer conversations with clients are associated with substantially higher odds of them subscribing to the term deposit.</span>
<span id="cb23-169"><a href="#cb23-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-170"><a href="#cb23-170" aria-hidden="true" tabindex="-1"></a>The standard error for the intercept is 0.02613 and for duration it is 0.00005482. Standard errors measure the uncertainty in the coefficient estimates. Smaller standard errors indicate more precise estimates. In our case, both standard errors are very small relative to the coefficient estimates, which reflects the fact that we have a large dataset (45,211 observations) and therefore a great deal of information for estimating the parameters.</span>
<span id="cb23-171"><a href="#cb23-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-172"><a href="#cb23-172" aria-hidden="true" tabindex="-1"></a>The z-value is computed by dividing each estimated coefficient by its standard error. For the intercept, $z = -3.193 / 0.02613 = -122.19$. For duration, $z = 0.003529 / 0.00005482 = 64.38$. The z-value plays the same role in logistic regression that the t-statistic plays in linear regression - it measures how many standard errors the estimated coefficient is from zero. Large absolute z-values indicate strong evidence that the true coefficient is not zero.</span>
<span id="cb23-173"><a href="#cb23-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-174"><a href="#cb23-174" aria-hidden="true" tabindex="-1"></a>The p-value for each coefficient tests the null hypothesis that the true coefficient equals zero, meaning that the predictor has no effect on the log-odds of the response. Both p-values in our output are reported as less than $2 \times 10^{-16}$. This means that the evidence against the null hypothesis is overwhelming - both the intercept and the duration coefficient are extremely statistically significant. The three asterisks next to each p-value confirm this, as they indicate significance at the 0.001 level, which is the most stringent threshold shown in the significance codes. For the duration predictor specifically, the tiny p-value tells us that there is an extremely strong statistical association between the length of the phone call and the probability of subscribing to the term deposit. This should not be surprising - a longer conversation gives the bank representative more time to explain the product, answer questions, and persuade the client.</span>
<span id="cb23-175"><a href="#cb23-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-176"><a href="#cb23-176" aria-hidden="true" tabindex="-1"></a>Below the coefficients table, R reports two measures of model fit called deviances.</span>
<span id="cb23-177"><a href="#cb23-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-178"><a href="#cb23-178" aria-hidden="true" tabindex="-1"></a>The null deviance measures how well the response variable is predicted by a model that includes only the intercept and no predictors. It is analogous to the total sum of squares in linear regression. The degrees of freedom for the null deviance equal the number of observations minus one (45,211 - 1 = 45,210). The null deviance represents the worst-case baseline - it tells us how poorly we predict if we ignore all predictor information and simply estimate the overall probability of subscription.</span>
<span id="cb23-179"><a href="#cb23-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-180"><a href="#cb23-180" aria-hidden="true" tabindex="-1"></a>The residual deviance measures how well the response is predicted by the model that includes the predictor duration. The degrees of freedom are reduced by one (because we have estimated one additional parameter beyond the intercept), giving 45,209. The residual deviance is substantially lower than the null deviance, which tells us that adding duration to the model meaningfully improves the fit. The reduction in deviance from 32,631 to 27,502 - a drop of 5,129 - represents the improvement in explanatory power gained by including call duration as a predictor. This difference approximately follows a chi-squared distribution with one degree of freedom under the null hypothesis that duration has no effect, and a drop of 5,129 is extraordinarily large, confirming what the p-value already told us.</span>
<span id="cb23-181"><a href="#cb23-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-182"><a href="#cb23-182" aria-hidden="true" tabindex="-1"></a>The AIC, or Akaike Information Criterion, is a measure of model quality that balances goodness of fit against model complexity. It is calculated as the residual deviance plus twice the number of estimated parameters. In our case, we estimated two parameters (the intercept and the duration coefficient), so $AIC = 27,502 + 2 \times 2 = 27,506$. The AIC is not interpretable in absolute terms - it only becomes useful when comparing two or more models fitted to the same data. A lower AIC indicates a better model, taking into account both how well the model fits and how many parameters it uses. We will use the AIC later when comparing the simple model to the multiple logistic regression model.</span>
<span id="cb23-183"><a href="#cb23-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-184"><a href="#cb23-184" aria-hidden="true" tabindex="-1"></a>Number of fisher scoring iterations tells us that the iterative algorithm used to maximise the likelihood function converged in 5 iterations. Fisher scoring is the numerical optimisation method that R uses internally to find the maximum likelihood estimates of the logistic regression coefficients. The fact that convergence occurred in only 5 iterations tells us that the estimation process was straightforward and that there were no numerical difficulties. If this number were very large or if R reported that the algorithm did not converge, it would be a sign of potential problems with the model, such as perfect separation of the classes.</span>
<span id="cb23-185"><a href="#cb23-185" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb23-186"><a href="#cb23-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-187"><a href="#cb23-187" aria-hidden="true" tabindex="-1"></a>In linear regression, the coefficients are estimated by the method of least squares, which finds the values of the coefficients that minimise the sum of squared differences between the observed and predicted values. In logistic regression, a different estimation method is used: **maximum likelihood estimation**. The intuition behind maximum likelihood is elegant. We want to find the values of the coefficients $\beta_0$ and $\beta_1$ that make the observed data as probable as possible. For each observation in our dataset, the model gives us a predicted probability that the client subscribes. For clients who actually did subscribe, we want this predicted probability to be high. For clients who did not subscribe, we want this predicted probability to be low (or equivalently, we want the predicted probability of not subscribing to be high). The likelihood function captures this idea formally: it is the product of the predicted probabilities for all the observations, where for each observation we use the predicted probability of the outcome that actually occurred.</span>
<span id="cb23-188"><a href="#cb23-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-189"><a href="#cb23-189" aria-hidden="true" tabindex="-1"></a>**Maximum likelihood estimation** finds the values of $\beta_0$ and $\beta_1$ that maximise this likelihood function. In practice, because working with products of many small probabilities is numerically inconvenient, we work with the logarithm of the likelihood - the **log-likelihood** - and maximise that instead. The maximisation is performed using an iterative numerical algorithm (typically iteratively reweighted least squares), which is handled automatically by the <span class="in">`glm()`</span> function in R.</span>
<span id="cb23-190"><a href="#cb23-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-191"><a href="#cb23-191" aria-hidden="true" tabindex="-1"></a>The key output of the estimation process is the set of estimated coefficients, along with their standard errors. The standard errors measure the uncertainty in the coefficient estimates, and they are used to construct confidence intervals and hypothesis tests. The z-statistic reported in the summary output is computed by dividing each estimated coefficient by its standard error, and the associated p-value tests the null hypothesis that the true coefficient is equal to zero - that is, that the predictor has no effect on the log-odds of the response.</span>
<span id="cb23-192"><a href="#cb23-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-193"><a href="#cb23-193" aria-hidden="true" tabindex="-1"></a>Once we have fitted a logistic regression model, we can use it to make predictions for new observations. In R, the <span class="in">`predict()`</span> function is used for this purpose. By default, <span class="in">`predict()`</span> applied to a glm object returns the predicted values on the scale of the linear predictor - that is, the predicted log-odds. To obtain predicted probabilities, we must specify <span class="in">`type = "response"`</span>.</span>
<span id="cb23-194"><a href="#cb23-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-195"><a href="#cb23-195" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip icon="false" collapse="true" title="Example: Making Predictions"}</span>
<span id="cb23-198"><a href="#cb23-198" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-199"><a href="#cb23-199" aria-hidden="true" tabindex="-1"></a>predicted_probabilities <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb23-200"><a href="#cb23-200" aria-hidden="true" tabindex="-1"></a>  logistic_simple,</span>
<span id="cb23-201"><a href="#cb23-201" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb23-202"><a href="#cb23-202" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-203"><a href="#cb23-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-204"><a href="#cb23-204" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predicted_probabilities)</span>
<span id="cb23-205"><a href="#cb23-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-206"><a href="#cb23-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-207"><a href="#cb23-207" aria-hidden="true" tabindex="-1"></a>This code produces the estimated probability of subscribing to the term deposit for each client in the dataset. Each value will be a number between 0 and 1. To convert these probabilities into class predictions, we apply a threshold - typically 0.5.</span>
<span id="cb23-208"><a href="#cb23-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-211"><a href="#cb23-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-212"><a href="#cb23-212" aria-hidden="true" tabindex="-1"></a>predicted_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probabilities <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"yes"</span>, <span class="st">"no"</span>)</span>
<span id="cb23-213"><a href="#cb23-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-214"><a href="#cb23-214" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> predicted_class, <span class="at">Actual =</span> bank_marketing_dataset<span class="sc">$</span>y)</span>
<span id="cb23-215"><a href="#cb23-215" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-216"><a href="#cb23-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-217"><a href="#cb23-217" aria-hidden="true" tabindex="-1"></a>This produces a confusion matrix, which is a cross-tabulation of the predicted class labels against the actual class labels. The confusion matrix tells us how many clients were correctly classified and how many were misclassified. We will explore the confusion matrix and related performance metrics in more detail later, but for now it is important to understand that this is the basic workflow of logistic regression: fit the model, extract predicted probabilities, apply a threshold, and evaluate the results.</span>
<span id="cb23-218"><a href="#cb23-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-219"><a href="#cb23-219" aria-hidden="true" tabindex="-1"></a>We can also make predictions for specific hypothetical clients. Suppose we want to know the predicted probability of subscription for a client whose last call lasted 300 seconds:</span>
<span id="cb23-220"><a href="#cb23-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-223"><a href="#cb23-223" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-224"><a href="#cb23-224" aria-hidden="true" tabindex="-1"></a>new_client <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">duration =</span> <span class="dv">300</span>)</span>
<span id="cb23-225"><a href="#cb23-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-226"><a href="#cb23-226" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(logistic_simple, <span class="at">newdata =</span> new_client, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb23-227"><a href="#cb23-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-228"><a href="#cb23-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-229"><a href="#cb23-229" aria-hidden="true" tabindex="-1"></a>This will return a single probability representing the model's estimate of how likely it is that a client with a 300-second phone call will subscribe to the term deposit.</span>
<span id="cb23-230"><a href="#cb23-230" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb23-231"><a href="#cb23-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-232"><a href="#cb23-232" aria-hidden="true" tabindex="-1"></a><span class="fu">### Multiple Logistic Regression</span></span>
<span id="cb23-233"><a href="#cb23-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-234"><a href="#cb23-234" aria-hidden="true" tabindex="-1"></a>In practice, we almost never rely on a single predictor. Multiple logistic regression extends the simple logistic regression model to include several predictors simultaneously. The logistic model generalises naturally: the log-odds of the response is modelled as a linear combination of all the predictors. If we have p predictors, the model is:</span>
<span id="cb23-235"><a href="#cb23-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-236"><a href="#cb23-236" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-237"><a href="#cb23-237" aria-hidden="true" tabindex="-1"></a>log(\frac{p(X)}{1 - p(X)}) = \beta_0 + \beta_0X_1 + \beta_2X_2 + ... + \beta_pX_p</span>
<span id="cb23-238"><a href="#cb23-238" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-239"><a href="#cb23-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-240"><a href="#cb23-240" aria-hidden="true" tabindex="-1"></a>Each coefficient represents the change in the log-odds of the response associated with a one-unit increase in predictor, holding all other predictors constant. This "holding all other predictors constant" interpretation is exactly the same as in multiple linear regression, and it is one of the most important aspects of the model for social science research, because it allows us to isolate the effect of each predictor after controlling for the others.</span>
<span id="cb23-241"><a href="#cb23-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-242"><a href="#cb23-242" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip icon="false" collapse="true" title="Example: Multiple Logistic Regression"}</span>
<span id="cb23-243"><a href="#cb23-243" aria-hidden="true" tabindex="-1"></a>In this model, we are predicting subscription using a rich set of demographic, financial, and campaign-related variables. Notice that several of these predictors are categorical (such as <span class="in">`job`</span>, <span class="in">`marital`</span>, <span class="in">`education`</span>, <span class="in">`housing`</span>, <span class="in">`loan`</span>, <span class="in">`contact`</span>, and <span class="in">`poutcome`</span>), and R automatically creates dummy variables for each category, choosing one category as the reference level.</span>
<span id="cb23-244"><a href="#cb23-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-247"><a href="#cb23-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-248"><a href="#cb23-248" aria-hidden="true" tabindex="-1"></a>logistic_multiple <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb23-249"><a href="#cb23-249" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> age <span class="sc">+</span> job <span class="sc">+</span> marital <span class="sc">+</span> education <span class="sc">+</span> balance <span class="sc">+</span> housing <span class="sc">+</span> loan <span class="sc">+</span> contact <span class="sc">+</span> duration <span class="sc">+</span> campaign <span class="sc">+</span> poutcome,</span>
<span id="cb23-250"><a href="#cb23-250" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bank_marketing_dataset,</span>
<span id="cb23-251"><a href="#cb23-251" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb23-252"><a href="#cb23-252" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-253"><a href="#cb23-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-254"><a href="#cb23-254" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic_multiple)</span>
<span id="cb23-255"><a href="#cb23-255" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-256"><a href="#cb23-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-257"><a href="#cb23-257" aria-hidden="true" tabindex="-1"></a>We can also compute predicted probabilities and class predictions from the multiple model in the same way as before:</span>
<span id="cb23-258"><a href="#cb23-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-261"><a href="#cb23-261" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-262"><a href="#cb23-262" aria-hidden="true" tabindex="-1"></a>predicted_probs_multiple <span class="ot">&lt;-</span> <span class="fu">predict</span>(logistic_multiple, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb23-263"><a href="#cb23-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-264"><a href="#cb23-264" aria-hidden="true" tabindex="-1"></a>predicted_class_multiple <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicted_probs_multiple <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"yes"</span>, <span class="st">"no"</span>)</span>
<span id="cb23-265"><a href="#cb23-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-266"><a href="#cb23-266" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> predicted_class_multiple, <span class="at">Actual =</span> bank_marketing_dataset<span class="sc">$</span>y)</span>
<span id="cb23-267"><a href="#cb23-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-268"><a href="#cb23-268" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb23-269"><a href="#cb23-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-270"><a href="#cb23-270" aria-hidden="true" tabindex="-1"></a>An important point to emphasise is that the coefficients in a multiple logistic regression model can differ substantially from those in a simple logistic regression model using the same predictor. This is because the multiple model controls for confounding - the relationships among the predictors themselves. A predictor that appears highly significant on its own may become non-significant once other variables are included in the model, or vice versa. This is a well-known phenomenon in regression analysis and underscores the importance of fitting models with multiple predictors rather than drawing conclusions from a series of simple models.</span>
<span id="cb23-271"><a href="#cb23-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-272"><a href="#cb23-272" aria-hidden="true" tabindex="-1"></a><span class="fu">### Multinomial Logistic Regression</span></span>
<span id="cb23-273"><a href="#cb23-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-274"><a href="#cb23-274" aria-hidden="true" tabindex="-1"></a>Everything we have discussed so far applies to the case where the response variable has exactly two categories. But what happens when the response variable has three or more categories? This is where multinomial logistic regression comes in. **Multinomial logistic regression** is a generalisation of binary logistic regression to situations where the response variable has K categories, where K is greater than two. The idea is to choose one of the K categories as a baseline or reference category, and then fit $K - 1$ separate logistic regression equations, each of which models the log-odds of being in a particular category relative to the reference category.</span>
<span id="cb23-275"><a href="#cb23-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-276"><a href="#cb23-276" aria-hidden="true" tabindex="-1"></a>For example, suppose we had a response variable with three categories: "subscribed to product A", "subscribed to product B", and "did not subscribe". If we choose "did not subscribe" as the baseline, then we would fit two logistic equations: one for the log-odds of subscribing to product A versus not subscribing, and another for the log-odds of subscribing to product B versus not subscribing. Each equation has its own set of coefficients, and the predicted probability of each outcome is computed using a generalisation of the logistic function called the **softmax function**.</span>
<span id="cb23-277"><a href="#cb23-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-278"><a href="#cb23-278" aria-hidden="true" tabindex="-1"></a>The softmax function ensures that the predicted probabilities for all K categories sum to one for each observation. For an observation with predictor values X, the probability of belonging to class k (for $k = 1, ..., K-1$) relative to the baseline class K is:</span>
<span id="cb23-279"><a href="#cb23-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-280"><a href="#cb23-280" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-281"><a href="#cb23-281" aria-hidden="true" tabindex="-1"></a>P(Y = k | X) = \frac{e^{\beta_{k0} + \beta_{k1}X_1 + ... + \beta_{kp}X_p}}{(1 + \sum_{l=1}^{K-1} e^(\beta_{l0} + \beta_{l1}X_1 + ... + \beta_{lp}X_p))}</span>
<span id="cb23-282"><a href="#cb23-282" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-283"><a href="#cb23-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-284"><a href="#cb23-284" aria-hidden="true" tabindex="-1"></a>The probability of the baseline class is:</span>
<span id="cb23-285"><a href="#cb23-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-286"><a href="#cb23-286" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-287"><a href="#cb23-287" aria-hidden="true" tabindex="-1"></a>P(Y = K | X) = \frac{1}{1 + \sum_{l=1}^{K-1} e^{\beta_{l0} + \beta_{l1}X_1 + ... + \beta_{lp}X_p}}</span>
<span id="cb23-288"><a href="#cb23-288" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb23-289"><a href="#cb23-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-290"><a href="#cb23-290" aria-hidden="true" tabindex="-1"></a>The interpretation of coefficients in multinomial logistic regression follows the same logic as in binary logistic regression, except that each coefficient refers to the effect of a predictor on the log-odds of a specific category relative to the baseline. This means that the output is more complex, but the fundamental idea remains the same.</span>
<span id="cb23-291"><a href="#cb23-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-292"><a href="#cb23-292" aria-hidden="true" tabindex="-1"></a>In our bank dataset, the response variable <span class="in">`y`</span> is binary, so we do not strictly need multinomial logistic regression. However, it is useful to see how it works in R, because many social science research questions involve multi-category outcomes. The <span class="in">`nnet`</span> package in R provides the <span class="in">`multinom()`</span> function for fitting multinomial logistic regression models.</span>
<span id="cb23-293"><a href="#cb23-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-294"><a href="#cb23-294" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip icon="false" collapse="true" title="Example: Multinomial Logistic Regression"}</span>
<span id="cb23-295"><a href="#cb23-295" aria-hidden="true" tabindex="-1"></a>In this case, because <span class="in">`y`</span> has only two levels, the multinomial model will produce results that are equivalent to binary logistic regression. But if the response had three or more levels, the output would include a separate row of coefficients for each non-reference category. The <span class="in">`multinom()`</span> function uses the first level of the factor as the reference category by default.</span>
<span id="cb23-296"><a href="#cb23-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-299"><a href="#cb23-299" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-300"><a href="#cb23-300" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb23-301"><a href="#cb23-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-302"><a href="#cb23-302" aria-hidden="true" tabindex="-1"></a>multinomial_model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(</span>
<span id="cb23-303"><a href="#cb23-303" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> age <span class="sc">+</span> duration <span class="sc">+</span> balance <span class="sc">+</span> education,</span>
<span id="cb23-304"><a href="#cb23-304" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> bank_marketing_dataset</span>
<span id="cb23-305"><a href="#cb23-305" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-306"><a href="#cb23-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-307"><a href="#cb23-307" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multinomial_model)</span>
<span id="cb23-308"><a href="#cb23-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-309"><a href="#cb23-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-310"><a href="#cb23-310" aria-hidden="true" tabindex="-1"></a>To obtain predicted class probabilities from a multinomial model, we use:</span>
<span id="cb23-311"><a href="#cb23-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-314"><a href="#cb23-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-315"><a href="#cb23-315" aria-hidden="true" tabindex="-1"></a>predicted_probs_multinomial <span class="ot">&lt;-</span> <span class="fu">predict</span>(multinomial_model, <span class="at">type =</span> <span class="st">"probs"</span>)</span>
<span id="cb23-316"><a href="#cb23-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-317"><a href="#cb23-317" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predicted_probs_multinomial)</span>
<span id="cb23-318"><a href="#cb23-318" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-319"><a href="#cb23-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-320"><a href="#cb23-320" aria-hidden="true" tabindex="-1"></a>And to obtain predicted class labels:</span>
<span id="cb23-321"><a href="#cb23-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-324"><a href="#cb23-324" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-325"><a href="#cb23-325" aria-hidden="true" tabindex="-1"></a>predicted_class_multinomial <span class="ot">&lt;-</span> <span class="fu">predict</span>(multinomial_model, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb23-326"><a href="#cb23-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-327"><a href="#cb23-327" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> predicted_class_multinomial, <span class="at">Actual =</span> bank_marketing_dataset<span class="sc">$</span>y)</span>
<span id="cb23-328"><a href="#cb23-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb23-329"><a href="#cb23-329" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb23-330"><a href="#cb23-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-331"><a href="#cb23-331" aria-hidden="true" tabindex="-1"></a><span class="fu">## Generative Models for Classification</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>